#!/usr/bin/env node
/**
 * scripts/trace-title.mjs — traces CALYPSO'S ODYSSEY (DESIGN-BIBLE §9.12) from Fraunces
 * wght 300 · opsz 144 · SOFT 0 · WONK 0 with opentype.js and writes the static path data
 * into src/art/gala-title.ts. Build-time only — never runs in the browser.
 *
 *   node scripts/trace-title.mjs            (downloads the variable TTF from google/fonts into the OS temp dir once)
 *   FRAUNCES_TTF=/path/to/Fraunces[SOFT,WONK,opsz,wght].ttf node scripts/trace-title.mjs
 */
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import otmod from 'opentype.js'
const ot = otmod.default || otmod

const FONT_URL = 'https://raw.githubusercontent.com/google/fonts/main/ofl/fraunces/Fraunces%5BSOFT%2CWONK%2Copsz%2Cwght%5D.ttf'
const OUT = new URL('../src/art/gala-title.ts', import.meta.url)
const SIZE = 100          // em in viewBox units
const TRACK = 0.06 * SIZE // .06em
const VB_W = 1000
const LINES = ["CALYPSO'S", 'ODYSSEY']
const BASELINES = [118, 236]
const TESSERA = 14

async function loadFont() {
  let file = process.env.FRAUNCES_TTF
  if (!file) {
    file = path.join(os.tmpdir(), 'mtf-fraunces-var.ttf')
    if (!fs.existsSync(file)) {
      console.log('downloading Fraunces …')
      const res = await fetch(FONT_URL)
      if (!res.ok) throw new Error(`font download failed: ${res.status}`)
      fs.writeFileSync(file, Buffer.from(await res.arrayBuffer()))
    }
  }
  const buf = fs.readFileSync(file)
  const font = ot.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength))
  font.variation.set({ wght: 300, opsz: 144, SOFT: 0, WONK: 0 })
  return font
}

const font = await loadFont()
const upem = font.unitsPerEm
const adv = g => ((font.variation.getTransform(g).advanceWidth ?? g.advanceWidth) / upem) * SIZE

const letters = []
let tessera = null
// opentype.js 2.0 returns NaN deltas when the same variable glyph is transformed twice, so trace each
// character once at the origin and translate the commands ourselves.
const cache = new Map()
const traced = ch => {
  if (!cache.has(ch)) cache.set(ch, font.charToGlyph(ch).getPath(0, 0, SIZE, {}, font).commands.map(c => ({ ...c })))
  return cache.get(ch)
}
const moved = (cmds, dx, dy) => cmds.map(c => {
  const o = { type: c.type }
  for (const k of ['x', 'x1', 'x2']) if (k in c) o[k] = c[k] + dx
  for (const k of ['y', 'y1', 'y2']) if (k in c) o[k] = c[k] + dy
  return o
}).map(c => c.type === 'Z' ? 'Z' : c.type === 'Q' ? `Q${c.x1.toFixed(1)} ${c.y1.toFixed(1)} ${c.x.toFixed(1)} ${c.y.toFixed(1)}` : c.type === 'C' ? `C${c.x1.toFixed(1)} ${c.y1.toFixed(1)} ${c.x2.toFixed(1)} ${c.y2.toFixed(1)} ${c.x.toFixed(1)} ${c.y.toFixed(1)}` : `${c.type}${c.x.toFixed(1)} ${c.y.toFixed(1)}`).join('')
LINES.forEach((text, line) => {
  // measure
  const glyphs = text.split('').map(ch => ({ ch, g: ch === "'" ? null : font.charToGlyph(ch) }))
  let width = 0
  glyphs.forEach((it, i) => {
    const w = it.g ? adv(it.g) : TESSERA * 1.6
    const kern = it.g && glyphs[i + 1]?.g ? (font.getKerningValue(it.g, glyphs[i + 1].g) / upem) * SIZE : 0
    it.w = w + kern
    width += it.w + (i < glyphs.length - 1 ? TRACK : 0)
  })
  let x = (VB_W - width) / 2
  const y = BASELINES[line]
  glyphs.forEach(it => {
    if (it.g) {
      const d = moved(traced(it.ch), x, y)
      if (/NaN/.test(d)) throw new Error(`NaN in glyph ${it.ch}`)
      letters.push({ ch: it.ch, line, d })
    } else {
      // the apostrophe becomes a gold tessera set where the mark would sit
      tessera = { x: +(x + (TESSERA * 1.6) / 2).toFixed(1), y: +(y - SIZE * 0.62).toFixed(1) }
    }
    x += it.w + TRACK
  })
})

const ts = `/**
 * §9.12 Gala lettering — CALYPSO'S ODYSSEY as SVG paths traced from Fraunces wght 300 · opsz 144 · SOFT 0 · WONK 0,
 * letter-spaced .06em, two lines; the apostrophe is a gold tessera (14 × 14, rotated 12°). Each letter has
 * pathLength="1": it is stroke-drawn (1 px cream) then filled, letter after letter, as \`--draw\` runs 0 → 1.
 * GENERATED by scripts/trace-title.mjs — do not edit the path data by hand; edit the script and re-run it.
 *
 *   galaTitle({ subtitle })   → SVG string (viewBox ${VB_W} × 340); subtitle = content.gala.subtitle (Fraunces italic <text>)
 *   draw(svg, p)              → sets --draw
 */
export const GALA_VIEWBOX = '0 0 ${VB_W} 340'
export const GALA_TESSERA = ${JSON.stringify(tessera)}
export const GALA_LETTERS: ReadonlyArray<{ ch: string; line: number; d: string }> = [
${letters.map(l => `  { ch: ${JSON.stringify(l.ch)}, line: ${l.line}, d: ${JSON.stringify(l.d)} },`).join('\n')}
]

const N = GALA_LETTERS.length + 1

export function galaTitle({ subtitle = 'The Greatest Journeys Are Not Always Across the Sea' }: { subtitle?: string } = {}): string {
  const paths = GALA_LETTERS.map((l, i) => \`<path class="gala-letter" data-ch="\${l.ch}" data-line="\${l.line}" style="--i:\${i}" d="\${l.d}" pathLength="1"/>\`).join('')
  const tIndex = GALA_LETTERS.findIndex(l => l.line === 1) // the tessera sits between the two words of line 0's end
  return \`<svg class="glyph glyph--gala" aria-hidden="true" viewBox="\${GALA_VIEWBOX}" preserveAspectRatio="xMidYMid meet" style="--draw:1">
  <style>
    .glyph--gala .gala-letter { --local: clamp(0, calc(var(--draw, 1) * 1.6 - var(--i, 0) * .04), 1); fill: var(--cream, #FFF7E1); fill-opacity: clamp(0, calc((var(--local) - .55) / .45), 1); stroke: var(--cream, #FFF7E1); stroke-width: 1; vector-effect: non-scaling-stroke; stroke-linejoin: round; stroke-dasharray: 1; stroke-dashoffset: calc(1 - var(--local)); stroke-opacity: clamp(0, calc(var(--local) * 4), 1); }
    .glyph--gala .gala-tessera { --local: clamp(0, calc(var(--draw, 1) * 1.6 - var(--i, 0) * .04), 1); fill: var(--gold, #D9A441); opacity: clamp(0, calc(var(--local) * 3), 1); }
    .glyph--gala .gala-sub { font: italic 300 26px var(--font-display, 'Fraunces', Georgia, serif); font-variation-settings: 'opsz' 144, 'SOFT' 12, 'WONK' 1; fill: var(--cream, #FFF7E1); opacity: clamp(0, calc((var(--draw, 1) - .7) / .3), 1); }
  </style>
  <g class="gala-lines">\${paths}</g>
  <rect class="gala-tessera" style="--i:\${tIndex - 1}" x="-7" y="-7" width="14" height="14" transform="translate(\${GALA_TESSERA.x} \${GALA_TESSERA.y}) rotate(12)"/>
  <text class="gala-sub" x="\${${VB_W} / 2}" y="306" text-anchor="middle">\${subtitle}</text>
</svg>\`
}

export function draw(svg: SVGElement, p: number): void { svg.style.setProperty('--draw', Math.min(1, Math.max(0, p)).toFixed(4)) }
`
fs.writeFileSync(OUT, ts)
console.log(`wrote ${path.relative(process.cwd(), OUT.pathname)} — ${letters.length} letters, tessera at`, tessera)
